channels:
  - conda-forge
dependencies:
  - damask=3.0.0
  - matplotlib
  - fenics
  - mshr
  - pyiron_base
  - pyiron_snippets >=0.1.0,<0.2.0
  - pyiron-data
  - pyvista
  - scipy
  - seaborn
  - pip:
    - git+https://github.com/pyiron/pyiron_continuum.git
