channels:
  - conda-forge
dependencies:
  - ase =3.22.1
  - coveralls =3.3.1
  - codacy-coverage =1.3.11
  - damask =3.0.0b
  - damask-grid =3.0.0b
  - damask-mesh =3.0.0b
  - k3d =2.16.1
  - matplotlib =3.8.4
  - numpy =1.26.4
  - pyiron =0.5.2
  - pyiron-data =0.0.29
  - python-damask =3.0.0b
  - scipy =1.11.4
  - scipy =1.13.0
  - seaborn =0.13.2
  - scikit-image =0.20.0
  - papermill =2.6.0
  - jupyter =1.0.0
  - fenics-dolfinx =0.8.0
  - mpich =4.2.1
  - pyvista =0.43.6
