channels:
  - conda-forge
dependencies:
  - ase
  - coveralls
  - coverage
  - codacy-coverage
  - python-damask
  - damask-mesh
  - damask-grid
  - damask=3.0.0*
  - matplotlib
  - numpy
  - pyiron
  - pyiron-data >=0.0.16
  - pyvista
  - scipy
  - seaborn
  - scikit-image
  - papermill
