channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.4
- numpy =1.26.4
- pyiron_base =0.8.2
- scipy =1.13.0
- sympy =1.12
- python-blosc2
- fenics-dolfinx =0.7.3
- mpich =4.2.1
- pyvista =0.43.5
