channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.4
- numpy =1.26.4
- pyiron =0.5.2
- scipy =1.13.0
- sympy =1.12
- python-blosc2
- python-damask =3.0.0b
