channels:
  - conda-forge
dependencies:
  - ase =3.22.1
  - damask-mesh =3.0.0b
  - damask-grid =3.0.0b
  - damask =3.0.0b
  - k3d
  - pyiron =0.5.0
  - pyiron-data
  - python-damask =3.0.0b
  - pyvista =0.42.3
  - seaborn =0.13.1
  - scikit-image =0.22.0
  - papermill
  - jupyter
