channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.4
- numpy =1.26.4
- pyiron_base =0.9.5
- pyiron_snippets =0.1.2
- scipy =1.14.0
- sympy =1.13.1
- python-blosc2
- python-damask =3.0.0b
- mendeleev =0.17.0
