channels:
  - conda-forge
dependencies:
  - ase
  - coveralls
  - codacy-coverage
  - damask
  - damask-grid
  - damask-mesh
  - k3d
  - matplotlib
  - numpy
  - pyiron
  - pyiron-data
  - python-damask
  - scipy
  - scipy
  - seaborn
  - scikit-image
  - papermill
  - jupyter
  - fenics-dolfinx
  - mpich
  - pyvista
