channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.4
- numpy =1.26.4
- pyiron_base =0.8.1
- scipy =1.13.0
- sympy =1.12
- python-blosc2
- damask-mesh =3.0.0b
- damask-grid =3.0.0b
- damask =3.0.0b
- python-damask =3.0.0b
