channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.9.1
- numpy =1.26.4
- pyiron_base =0.9.10
- pyiron_snippets =0.1.3
- scipy =1.14.0
- sympy =1.13.0
- python-blosc2
- python-damask =3.0.0b
- mendeleev =0.17.0
