channels:
  - conda-forge
dependencies:
  - ase =3.22.1
  - fenics =2019.1.0
  - fenics =2019.1.0=*_42
  - mshr
  - k3d
  - pyiron =0.5.0
  - pyiron-data =0.0.26
  - pyvista =0.42.3
  - seaborn =0.13.1
  - scikit-image =0.22.0
  - papermill
  - jupyter
