channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- coveralls
- atomistics =0.1.32
- coverage
- codacy-coverage
- matplotlib =3.9.2
- numpy =1.26.4
- pyiron_base =0.9.12
- pyiron_snippets =0.1.4
- scipy =1.14.1
- sympy =1.13.2
- python-blosc2
- python-damask =3.0.0b
- mendeleev =0.17.0
