name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_damask:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  - uses: pyiron/actions/cached-mamba@main
    with:
      python-version: "3.11"
      env-prefix: "ubuntu-latest"
      env-label: "ubuntu-latest-py3_11" 
      env-files: .ci_support/environment.yml .ci_support/environment-notebooks-damask.yml
    - name: Tests
      shell: bash -l {0}
      run: ./.ci_support/build_notebooks_damask.sh
  build_fenics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: "3.11"
        mamba-version: "*"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
        mamba env update --name test --file .ci_support/environment-notebooks-fenics.yml
    - name: Tests
      shell: bash -l {0}
      run: ./.ci_support/build_notebooks_fenics.sh
