name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pyiron/actions/build-notebooks@main
        with:
          python-version: '3.11'
          env-files: .ci_support/environment-notebooks.yml
          exclusion-file: .ci_support/exclude