name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  build-notebooks:
    if: |
      github.event_name == 'push' ||
      ( github.event_name == 'pull_request'  && contains(github.event.pull_request.labels.*.name, 'integration' ))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pyiron/actions/build-notebooks@actions-3.1.0
        with:
          python-version: '3.11'
          env-files: .ci_support/environment-notebooks-integration.yml
          exclusion-file: .ci_support/exclude