# This runs jobs on labels being found

name: PR labeled

on:
  pull_request:
    types: [labeled]

jobs:
  notebooks:
    if: contains(github.event.pull_request.labels.*.name, 'integration' )
    uses: ./.github/workflows/integrationtest.yml