# This runs jobs which pyiron modules should run on release
# This job runs on pull requests and does not actually publish anything to pypi
# It is useful for debugging new build recipes
# To actually release, change the `on` and `publish-to-pypi` fields
name: Preview Release

on:
  pull_request:
#  release:
#    types: [ published ]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/pyproject-release.yml@actions-3.1.0
    secrets: inherit
    with:
      semantic-upper-bound: 'minor'
      publish-to-pypi: false