
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CONDA_PREFIX: /usr/share/miniconda/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: "3.11"
        mamba-version: "*"
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        environment-file: .ci_support/environment-pypi-unit.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      run: coverage run --omit pyiron_continuum/_version.py -m unittest discover tests/unit
    - name: Coverage
      continue-on-error: True
      shell: bash -l {0}
      run: |
        coverage combine
        coveralls
        coverage xml
